### ISSUE TITLE
 del.sync(...).then is not a function

### ISSUE THREAD

**Issue by GaziTaufiqIslam** [zellwk/gulp-starter-csstricks#16]
When I run `gulp clean` it gives me the following error:

` TypeError: del.sync(...).then is not a function
    at Gulp.<anonymous> (F:\UEM\dev\ureckon19-website - Copy\gulpfile.js:85:27)
    at module.exports (F:\UEM\dev\ureckon19-website - Copy\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (F:\UEM\dev\ureckon19-website - Copy\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (F:\UEM\dev\ureckon19-website - Copy\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (F:\UEM\dev\ureckon19-website - Copy\node_modules\orchestrator\index.js:134:8)
    at C:\Users\farhana\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)`

Although it returns an error yet the `dist` folder is deleted.

**Comment by EnzoBatista** [comment]
@GaziTaufiqIslam have you already solved it?
You might use a callback function something like that:

gulp.task('clean:dist', function(done) {
  del.sync('dist');
  done();
})

gulp.task('build', function (done) {
   runSequence(
      'clean:dist',
      'sass', 'useref', 'images', 'fonts'
    ), done();
  })
