### ISSUE TITLE
After npm install, running gulp returns this error.

### ISSUE THREAD

**Issue by dylandgeorge** [zellwk/gulp-starter-csstricks#9]
`/gulpfile.js:92
  runSequence(['sass', 'browserSync'] 'watch',
                                    ^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:17:3)`

**Comment by zellwk** [comment]
Accidentally merged with an error. Should work now.

**Comment by zellwk** [comment]
See #8
